import { ResearchProject } from '@/types/research';

export const MOCK_RESEARCH_LIST: ResearchProject[] = [
  {
    id: 'mock-1',
    title: 'AI-Assisted Crop Disease Detection for Smart Farming',
    abstract:
      'A lightweight computer vision pipeline that identifies common crop diseases from leaf images for early intervention.',
    publication_year: 2025,
    status: 'published',
    created_by: 'mock-user',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: 'cat-cs', name: 'Computer Science', created_at: new Date().toISOString() },
    authors: [{ id: 'a1', research_id: 'mock-1', author_name: 'Liam Carter', author_order: 1, created_at: new Date().toISOString() }],
    keywords: [],
    files: [],
    download_count: 128,
  },
  {
    id: 'mock-2',
    title: 'Renewable Microgrid Optimization for Campus Energy Systems',
    abstract:
      'This study models energy demand and proposes a hybrid solar-battery scheduling strategy for lower peak consumption.',
    publication_year: 2024,
    status: 'approved',
    created_by: 'mock-user',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: 'cat-eng', name: 'Engineering', created_at: new Date().toISOString() },
    authors: [{ id: 'a2', research_id: 'mock-2', author_name: 'Sophia Nguyen', author_order: 1, created_at: new Date().toISOString() }],
    keywords: [],
    files: [],
    download_count: 93,
  },
  {
    id: 'mock-3',
    title: 'Learning Analytics Dashboard for Student Success Prediction',
    abstract:
      'An analytics framework using attendance and LMS behavior to forecast at-risk students with explainable metrics.',
    publication_year: 2024,
    status: 'published',
    created_by: 'mock-user',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: 'cat-edu', name: 'Education', created_at: new Date().toISOString() },
    authors: [{ id: 'a3', research_id: 'mock-3', author_name: 'Ethan Ramos', author_order: 1, created_at: new Date().toISOString() }],
    keywords: [],
    files: [],
    download_count: 77,
  },
  {
    id: 'mock-4',
    title: 'Blockchain Traceability Model for Agricultural Supply Chains',
    abstract:
      'A permissioned ledger model that tracks farm-to-market product provenance with reduced verification overhead.',
    publication_year: 2023,
    status: 'approved',
    created_by: 'mock-user',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: 'cat-biz', name: 'Business', created_at: new Date().toISOString() },
    authors: [{ id: 'a4', research_id: 'mock-4', author_name: 'Mia Patel', author_order: 1, created_at: new Date().toISOString() }],
    keywords: [],
    files: [],
    download_count: 64,
  },
  {
    id: 'mock-5',
    title: 'Community Health Risk Mapping with Geospatial Indicators',
    abstract:
      'Geospatial analysis of environmental and demographic indicators to improve localized public health response planning.',
    publication_year: 2023,
    status: 'published',
    created_by: 'mock-user',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: 'cat-med', name: 'Medicine', created_at: new Date().toISOString() },
    authors: [{ id: 'a5', research_id: 'mock-5', author_name: 'Noah Bennett', author_order: 1, created_at: new Date().toISOString() }],
    keywords: [],
    files: [],
    download_count: 142,
  },
];

